### ISSUE TITLE
Add option to manually specify upper bound of spectrum in `bf_lbo`

### ISSUE THREAD

**Issue by pbeckman** [sampotter/butterfly#22]
This would give us more control over the domain in spectral space where we build the frequency tree, which is especially helpful when considering incongruous h- or p-refined meshes of the same underlying manifold.

**Comment by sampotter** [comment]
@pbeckman OK, I added this option and mucked around with `bf_lbo`'s CLI args, their help, etc.

Please scrutinize this invocation and the output... The results are much more encouraging and reasonable:
```sh
./bf_lbo --useOctree --freqMax=4000 --rowTreeInitDepth=1 --freqTreeMaxDepth=3 --objPath=path/to/e.g./dragon1.obj
```
