### ISSUE TITLE
Request for Graduate Studies Recommendation Letter--Annika

### ISSUE THREAD

**Issue by annikagqy** [sampotter/butterfly#4]
Dear Professor Potter,

I hope this message finds you well. My name is Annika Gu, and I am reaching out to you through this unusual way as I have found it challenging to reach you via email or in person...I am currently in the process of applying for graduate studies and am seeking your support in writing a recommendation letter. I have sent necessary materials and program links to your nyu email, but I haven't receive any reply yet. As the deadline is approaching, I sincerely hope this message reaches you and that you might consider my request favorably.

Thank you very much for your time and consideration. I am hopeful for a positive response and eagerly await your response. 

Best, 
Annika Gu

**Comment by lgreengard** [comment]
Hi,I will try to get this to Sam...LGSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: annikagqy ***@***.***> Date: 11/15/23  11:45 PM  (GMT-05:00) To: sampotter/butterfly ***@***.***> Cc: Subscribed ***@***.***> Subject: [sampotter/butterfly] Request for Graduate Studies Recommendation Letter--Annika (Issue #4) 
Dear Professor Potter,
I hope this message finds you well. My name is Annika Gu, and I am reaching out to you through this unusual way as I have found it challenging to reach you via email or in person...I am currently in the process of applying for graduate studies and am seeking your support in writing a recommendation letter. I have sent necessary materials and program links to your nyu email, but I haven't receive any reply yet. As the deadline is approaching, I sincerely hope this message reaches you and that you might consider my request favorably.
Thank you very much for your time and consideration. I am hopeful for a positive response and eagerly await your response.
Best,
Annika Gu

**Comment by sampotter** [comment]
@lgreengard I'm aware of this. I've replied to Annika by email. Thanks!
